# Generated by Django 6.1 on 2026-08-24 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("law", "Law"),
                            ("regulation", "Regulation"),
                            ("bylaw", "Bylaw"),
                            ("circular", "Circular"),
                            ("decree", "Decree"),
                            ("resolution", "Resolution"),
                            ("executive_resolution", "Executive Resolution"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("issuing_authority", models.CharField(blank=True, max_length=500)),
                ("approval_date", models.CharField(blank=True, max_length=20)),
                ("publication_date", models.CharField(blank=True, max_length=20)),
                ("effective_date", models.CharField(blank=True, max_length=20)),
                ("subject", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("repealed", "Repealed"),
                            ("amended", "Amended"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LegalEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("canonical_title", models.TextField()),
                ("entity_type", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LegalElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "element_type",
                    models.CharField(
                        choices=[
                            ("structural", "Structural"),
                            ("provision", "Provision"),
                        ],
                        max_length=30,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="legal.legaldocument",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="legal.legalelement",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="legal.legalentity",
            ),
        ),
        migrations.CreateModel(
            name="LegalProvision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provision_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("note", "Note"),
                            ("clause", "Clause"),
                            ("subclause", "Subclause"),
                            ("item", "Item"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=50)),
                ("title", models.TextField(blank=True)),
                ("text", models.TextField()),
                (
                    "element",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provision",
                        to="legal.legalelement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegalRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("amends", "Amends"),
                            ("modifies", "Modifies"),
                            ("repeals", "Repeals"),
                            ("replaces", "Replaces"),
                            ("references", "References"),
                            ("adds", "Adds"),
                            ("conflicts", "Conflicts"),
                            ("identical", "Identical"),
                            ("related", "Related"),
                        ],
                        max_length=50,
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="legal.legalprovision",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="legal.legalprovision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RelationshipContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_text", models.TextField(blank=True)),
                ("target_text", models.TextField(blank=True)),
                ("old_text", models.TextField(blank=True)),
                ("new_text", models.TextField(blank=True)),
                ("source_date", models.CharField(blank=True, max_length=20)),
                ("target_date", models.CharField(blank=True, max_length=20)),
                ("effective_date", models.CharField(blank=True, max_length=20)),
                ("reference_docs", models.JSONField(blank=True, default=list)),
                ("reference_provisions", models.JSONField(blank=True, default=list)),
                ("evidence", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contexts",
                        to="legal.legalrelationship",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("nezamat", "Nezamat"),
                            ("rrk", "RRK"),
                            ("qavanin", "Qavanin"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("source_id", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.URLField(max_length=2000)),
                ("title", models.TextField()),
                ("raw_path", models.TextField(blank=True)),
                ("json_path", models.TextField(blank=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("crawled_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source", "source_id"],
                        name="legal_sourc_source_1f0937_idx",
                    ),
                    models.Index(
                        fields=["processing_status"],
                        name="legal_sourc_process_0d533a_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "source_id"), name="unique_source_document_id"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LegalVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("valid_from", models.CharField(blank=True, max_length=20)),
                ("valid_until", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("current", "Current"),
                            ("superseded", "Superseded"),
                            ("invalid", "Invalid"),
                        ],
                        default="current",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="legal.legalprovision",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="legal.sourcedocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="legal.legaldocument",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legal_documents",
                        to="legal.sourcedocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StructuralElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "structural_type",
                    models.CharField(
                        choices=[
                            ("book", "Book"),
                            ("part", "Part"),
                            ("chapter", "Chapter"),
                            ("section", "Section"),
                            ("subsection", "Subsection"),
                            ("introduction", "Introduction"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.TextField(blank=True)),
                ("number", models.CharField(blank=True, max_length=50)),
                (
                    "element",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structural",
                        to="legal.legalelement",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="legalelement",
            index=models.Index(
                fields=["document", "parent", "order"],
                name="legal_legal_documen_7c5946_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="legalelement",
            index=models.Index(
                fields=["document", "element_type"],
                name="legal_legal_documen_2127b5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalelement",
            constraint=models.UniqueConstraint(
                fields=("document", "parent", "order"),
                name="unique_element_order_per_parent",
            ),
        ),
        migrations.AddIndex(
            model_name="legaldocument",
            index=models.Index(
                fields=["document_type", "status"],
                name="legal_legal_documen_f7bf8e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="legalprovision",
            index=models.Index(
                fields=["provision_type"], name="legal_legal_provisi_b0015e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="legalrelationship",
            index=models.Index(
                fields=["source", "relationship_type"],
                name="legal_legal_source__1b6609_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="legalrelationship",
            index=models.Index(
                fields=["target", "relationship_type"],
                name="legal_legal_target__8cd7f3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalrelationship",
            constraint=models.UniqueConstraint(
                fields=("source", "target", "relationship_type"),
                name="unique_legal_relationship",
            ),
        ),
        migrations.AddIndex(
            model_name="legalversion",
            index=models.Index(
                fields=["provision", "status"], name="legal_legal_provisi_c318b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentsource",
            index=models.Index(
                fields=["document", "is_primary"], name="legal_docum_documen_4a815b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsource",
            constraint=models.UniqueConstraint(
                fields=("document", "source_document"), name="unique_document_source"
            ),
        ),
    ]
