# Generated by Django 6.1 on 2026-08-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sourcedocument",
            name="crawled_at",
        ),
        migrations.RemoveField(
            model_name="sourcedocument",
            name="raw_path",
        ),
        migrations.RemoveField(
            model_name="sourcedocument",
            name="rejection_reason",
        ),
        migrations.AlterField(
            model_name="legalprovision",
            name="provision_type",
            field=models.CharField(
                choices=[
                    ("article", "Article"),
                    ("note", "Note"),
                    ("clause", "Clause"),
                    ("subclause", "Subclause"),
                    ("item", "Item"),
                    ("table", "Table"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
