# Generated by Django 6.1 on 2026-08-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0002_remove_sourcedocument_crawled_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="legaldocument",
            name="hierarchy_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("constitution", "قانون اساسی"),
                    ("ordinary_law", "قانون عادی"),
                    ("executive_regulation", "مقررات قوه مجریه"),
                    ("circular", "بخشنامه"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
