# Generated by Django 6.1 on 2026-08-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0003_legaldocument_hierarchy_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcedocument",
            name="source",
            field=models.CharField(
                choices=[
                    ("nezamat", "Nezamat"),
                    ("rrk", "RRK"),
                    ("qavanin", "Qavanin"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="nezamat",
                max_length=50,
            ),
        ),
    ]
