# Generated by Django 6.1 on 2026-08-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0004_alter_sourcedocument_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legaldocument",
            name="hierarchy_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("constitution", "Constitution"),
                    ("ordinary_law", "OrdinaryLaw"),
                    ("executive_regulation", "ExecutiveRegulation"),
                    ("circular", "Circular"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
