# Generated by Django 6.1 on 2026-09-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0005_alter_legaldocument_hierarchy_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="legaldocument",
            name="document_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
