# Generated by Django 6.1 on 2026-09-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0006_legaldocument_document_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legaldocument",
            name="document_id",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
