# Generated by Django 6.1 on 2026-09-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0009_alter_legaldocument_document_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="legalversion",
            old_name="valid_from",
            new_name="version_date",
        ),
        migrations.RemoveField(
            model_name="legalversion",
            name="valid_until",
        ),
        migrations.AlterField(
            model_name="legalprovision",
            name="provision_type",
            field=models.CharField(
                choices=[
                    ("article", "Article"),
                    ("note", "Note"),
                    ("clause", "Clause"),
                    ("subclause", "Subclause"),
                    ("item", "Item"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="legalversion",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("current", "Current"),
                    ("superseded", "Superseded"),
                    ("invalid", "Invalid"),
                ],
                max_length=50,
            ),
        ),
    ]
