# Generated by Django 6.1 on 2026-09-02 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0010_rename_valid_from_legalversion_version_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="legalversion",
            name="source",
        ),
    ]
