# Generated by Django 5.2.17 on 2026-09-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0012_alter_documentsource_id_alter_legaldocument_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legalprovision",
            name="provision_type",
            field=models.CharField(
                choices=[
                    ("constitutional_principle", "Constitutional Principle"),
                    ("article", "Article"),
                    ("note", "Note"),
                    ("clause", "Clause"),
                    ("subclause", "Subclause"),
                    ("item", "Item"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
