# Generated by Django 5.2.17 on 2026-09-17 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0014_alter_documentsource_id_alter_legaldocument_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalrelationship',
            name='relationship_type',
            field=models.CharField(choices=[('amends', 'Amends'), ('modifies', 'Modifies'), ('adds', 'Adds'), ('removes', 'Removes'), ('replaces', 'Replaces'), ('repeals', 'Repeals'), ('cancels', 'Cancels'), ('annuls', 'Annuls'), ('suspends', 'Suspends'), ('revives', 'Revives'), ('extends', 'Extends'), ('expires', 'Expires'), ('conflicts', 'Conflicts'), ('takhsis', 'Takhsis'), ('taqyid', 'Taqyid'), ('takhassos', 'Takhassos'), ('hokumat', 'Hokumat'), ('references', 'References'), ('elaborates', 'Elaborates'), ('implements', 'Implements'), ('identical', 'Identical')], max_length=50),
        ),
        migrations.CreateModel(
            name='LegalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('interpretation', 'Interpretation'), ('judicial_decision', 'Judicial Decision'), ('legal_opinion', 'Legal Opinion'), ('takhsis', 'Takhsis'), ('taqyid', 'Taqyid'), ('takhassos', 'Takhassos'), ('annulment', 'Annulment'), ('expiration', 'Expiration'), ('other', 'Other')], max_length=50)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='legal.legalprovision')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='legal.legaldocument')),
            ],
            options={
                'indexes': [models.Index(fields=['provision', 'note_type'], name='legal_legal_provisi_4714a3_idx'), models.Index(fields=['source_document', 'note_type'], name='legal_legal_source__b67fd6_idx')],
            },
        ),
    ]
