# Generated by Django 5.2.17 on 2026-09-19 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0015_alter_legalrelationship_relationship_type_legalnote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentSource',
        ),
    ]
