# Generated by Django 5.2.17 on 2026-09-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0016_delete_documentsource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationshipcontext',
            name='source_date',
        ),
        migrations.RemoveField(
            model_name='relationshipcontext',
            name='source_text',
        ),
        migrations.RemoveField(
            model_name='relationshipcontext',
            name='target_date',
        ),
        migrations.RemoveField(
            model_name='relationshipcontext',
            name='target_text',
        ),
    ]
